const nodemailer = require('nodemailer');
require('dotenv').config();

const transporter = nodemailer.createTransport({
  host: process.env.SMTP_HOST,
  port: process.env.SMTP_PORT,
  secure: false, // true for 465, false for other ports
  auth: {
    user: process.env.SMTP_USER,
    pass: process.env.SMTP_PASS,
  },
});

function generateHtmlEmail(jobs) {
  if (!jobs || jobs.length === 0) {
    return `
      <div style="font-family: Arial, sans-serif; max-width: 800px; margin: auto;">
        <h2 style="color: #333;">Daily Job Scraper Report</h2>
        <p style="color: #d9534f; font-weight: bold;">No jobs were dynamically found today!</p>
        <p>This usually means the job boards (Naukri, LinkedIn, Indeed) blocked the GitHub Actions scraper due to Cloud/Bot protection.</p>
        <p>Your scheduled cron job successfully ran at 8:00 AM, but returned 0 results.</p>
      </div>
    `;
  }

  let tableRows = jobs.map((job, index) => {
    return `
      <tr>
        <td style="padding: 10px; border-bottom: 1px solid #eee;">${index + 1}</td>
        <td style="padding: 10px; border-bottom: 1px solid #eee;"><strong>${job.title}</strong></td>
        <td style="padding: 10px; border-bottom: 1px solid #eee;">${job.company}</td>
        <td style="padding: 10px; border-bottom: 1px solid #eee;">${job.source}</td>
        <td style="padding: 10px; border-bottom: 1px solid #eee;">
          <a href="${job.url}" style="background-color: #007bff; color: white; padding: 5px 10px; text-decoration: none; border-radius: 4px;">View</a>
        </td>
      </tr>
    `;
  }).join('');

  return `
    <div style="font-family: Arial, sans-serif; max-width: 800px; margin: auto;">
      <h2 style="color: #333;">Top Fresher Software Jobs in Chennai Today</h2>
      <p>Here are the top ${jobs.length} job openings curated from Naukri, LinkedIn, and Indeed:</p>
      
      <table style="width: 100%; border-collapse: collapse; margin-top: 20px;">
        <thead>
          <tr style="background-color: #f8f9fa; text-align: left;">
            <th style="padding: 10px; border-bottom: 2px solid #ddd;">#</th>
            <th style="padding: 10px; border-bottom: 2px solid #ddd;">Job Title</th>
            <th style="padding: 10px; border-bottom: 2px solid #ddd;">Company</th>
            <th style="padding: 10px; border-bottom: 2px solid #ddd;">Source</th>
            <th style="padding: 10px; border-bottom: 2px solid #ddd;">Action</th>
          </tr>
        </thead>
        <tbody>
          ${tableRows}
        </tbody>
      </table>
      
      <p style="margin-top: 30px; font-size: 12px; color: #777;">
        This email was automatically generated by your daily job scraper bot.
      </p>
    </div>
  `;
}

async function sendEmail(jobs) {
  // We removed the block that prevented sending an email for 0 jobs
  const htmlContent = generateHtmlEmail(jobs);
  const toEmail = process.env.RECEIVER_EMAIL;

  if (!toEmail || toEmail === 'your_email@gmail.com') {
    console.error('Receiver email not configured properly in .env');
    return;
  }

  try {
    const info = await transporter.sendMail({
      from: `"Job Scraper Bot" <${process.env.SMTP_USER}>`,
      to: toEmail,
      subject: `Daily Top ${jobs.length} Fresher Software Jobs in Chennai`,
      html: htmlContent,
    });
    console.log('Message sent: %s', info.messageId);
  } catch (error) {
    console.error('Error sending email:', error.message);
  }
}

module.exports = { sendEmail };
